### PR TITLE
Update the education and training links

### PR DESCRIPTION
**Pull request by hackygolucky**
Updates for new projects and training available to Node.js project.

### CODE REVIEW

**Comment by vvscode** [comment]
what's wrong with Tracy?

**Comment by addaleax** [comment]
@vvscode I’ve deleted your comment because it seemed like it might violate our [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md).

If you have any questions regarding the changes here, could you try to re-phrase those, and/or point to the parts of the diff that you have concerns about?

**Comment by vvscode** [comment]
well, pull request title says that it adds links, however it also removes some mentions for the person

**Comment by ghost** [comment]
@vvscode that's because the person in question (Tracy) isn't employed by the Node.js Foundation anymore and therefore can't be formally listed here 😄

**Comment by vvscode** [comment]
I see, just supposed that it should be separate PR )

**Review by fhinkel — APPROVED** [review]

**Comment by refack** [comment]
Was spelunking for information about the certification program and found this, thought it best to merge.

@hackygolucky is there any follow up info?

**Pull request merged**
