### PR TITLE
Certification branch added where on can find certification related stuffs

### PR DESCRIPTION
**Pull request by sumn2u**
Instead on putting all stuffs in education it would be better to make separate branch and merge to master after verified its content so i create this branch.

### CODE REVIEW

**Comment by sumn2u** [comment]
@hackygolucky can you have a look on it ?

**Comment by martinheidegger** [comment]
Note: the branch has conflicts.

**Comment by sumn2u** [comment]
@martinheidegger  give me few minutes

**Comment by sumn2u** [comment]
@martinheidegger new pull request https://github.com/nodejs/education/pull/12

**Pull request closed without merging**
